language: crystal
install:
  - shards install
script:
  - crystal spec -D spec
  - crystal docs
  - bin/ameba
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: CrystalFTP
  on:
    branch: master
  local_dir: docs
